# https://goreleaser.com/customization/homebrew/

brews:
  - tap:
      owner: wa-lang
      name: homebrew-tap
    url_template: "https://github.com/wa-lang/wa/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: WaReleaser Bot
      email: dev@wa-lang.org
    folder: HomebrewFormula
    homepage: "https://github.com/wa-lang/wa"
    description: "The Wa Programming Language"
    license: "AGPL-v3 License"
    skip_upload: false
    test: |
      system "#{bin}/wa -v"

